export const settings = {
    // Increment to induce migrations which can be controlled with the migration manager
    breakingVersion: 109,
    // Default values, do not change. Instead modify clones in memory
    roomVisuals: false,
    baseVisuals: false,
    dataVisuals: false,
    mapVisuals: false,
    CPULogging: false,
    roomStats: 2,
    allyPlayers: [
        'MarvinTMB',
        'PandaMaster',
        'lokenwow',
        'LittleBitBlue',
        'DefaultO',
        'Allorrian',
        'Aerics',
        'PlaidRabbit',
        'SokarNox',
        'Amberdark',
    ],
    nonAggressionPlayers: ['Q13214', 'HerrKai', 'Raggy', 'somygame', 'shley92822212'],
    tradeBlacklist: [],
    pixelSelling: false,
    pixelGeneration: false,
    autoClaim: true,
    autoAttack: false,
    publicRamparts: false,
    allyTrading: true,
    marketUsage: true,
    logging: false,
    creepSay: true,
    creepChant: true,
    simpleAlliesSegment: 90,
    errorExporting: false,
    structureMigration: true,
};
