{
 "title": "Screeps MMO Shard2",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "60s",
 "templating": {
  "list": [
   { "name": "data", "label": "data", "query": "screeps.privateserver.cpuUsage" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "movingAverage(screeps.privateserver.cpuUsage, '1d')"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "screeps.privateserver.memoryUsage"
    }
   ]
  },
  {
   "title": "GCL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "screeps.privateserver.GCLLevel" }
   ]
  },
  {
   "title": "GCL Percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "screeps.privateserver.GCLPercent"
    }
   ]
  },
  {
   "title": "Avg Energy Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(movingAverage(screeps.privateserver.energyHarvested, '1d'), 3)"
    },
    {
     "target": "aliasByNode(movingAverage(screeps.privateserver.controlPoints, '1d'), 3)"
    },
    {
     "target": "aliasByNode(movingAverage(screeps.privateserver.energySpentOnConstruction, '1d'), 3)"
    },
    {
     "target": "aliasByNode(movingAverage(screeps.privateserver.energySpentOnRepairing, '1d'), 3)"
    },
    {
     "target": "aliasByNode(movingAverage(screeps.privateserver.energySpentOnBarricades, '1d'), 3)"
    },
    {
     "target": "aliasByNode(movingAverage(screeps.privateserver.energySpentOnCreeps, '1d'), 3)"
    },
    {
     "target": "aliasByNode(movingAverage(screeps.privateserver.energySpentOnPower, '1d'), 3)"
    },
    {
     "target": "aliasByNode(movingAverage(creeps.marvintmb.shard.energySpentByLinks, '1d'), 3)"
    }
   ]
  },
  {
   "title": "Communes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "screeps.privateserver.communes" }
   ]
  },
  {
   "title": "Credits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "screeps.privateserver.credits" }
   ]
  },
  {
   "title": "GPL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "screeps.privateserver.GPLLevel" }
   ]
  },
  {
   "title": "GPL Percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "screeps.privateserver.GPLPercent"
    }
   ]
  },
  {
   "title": "Total Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "target": "aliasByNode(screeps.privateserver.energy, 3)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(screeps.privateserver.cpuUsage, 3)"
    },
    {
     "target": "alias(movingAverage(screeps.privateserver.cpuUsage, '1d'), 'avg cpuUsage')"
    },
    {
     "target": "aliasByNode(screeps.privateserver.cpuLimit, 3)"
    }
   ]
  },
  {
   "title": "CPU Bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(screeps.privateserver.cpuBucket, 3)"
    }
   ]
  },
  {
   "title": "GCL Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(screeps.privateserver.GCLPercent, 3)"
    }
   ]
  },
  {
   "title": "Total GCL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(screeps.privateserver.totalGCL, 3)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(screeps.privateserver.memoryUsage, 3)"
    },
    {
     "target": "alias(movingAverage(screeps.privateserver.memoryUsage, '1d'), 'avg memoryUsed')"
    }
   ]
  },
  {
   "title": "All",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(screeps.privateserver.*, 3)"
    }
   ]
  },
  {
   "title": "Market Averages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(screeps.privateserver.marketAverages.*, '1d'), 4)"
    }
   ]
  },
  {
   "title": "My Creeps Per Room",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(screeps.privateserver.roomManager.*.myCreeps, '1d'), 4)"
    }
   ]
  },
  {
   "title": "CPU Per Commune",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(screeps.privateserver.cpuPerCommune, 3)"
    },
    {
     "target": "alias(movingAverage(screeps.privateserver.cpuPerCommune, '1d'), 'avg cpuPerCommune')"
    }
   ]
  },
  {
   "title": "Stored Energy Per Room",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(screeps.privateserver.roomManager.*.storedEnergy, '1d'), 4)"
    }
   ]
  },
  {
   "title": "roomManager CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(screeps.privateserver.roomManager.*.cpuUsage, '1d'), 4)"
    }
   ]
  },
  {
   "title": "Avg Time Spent Spawning",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "screeps.privateserver.avgTimeSpentSpawning"
    },
    {
     "target": "movingAverage(screeps.privateserver.avgTimeSpentSpawning, '1d')"
    }
   ]
  },
  {
   "title": "GPL Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(screeps.privateserver.GPLPercent, 3)"
    }
   ]
  },
  {
   "title": "Total GPL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(screeps.privateserver.totalGPL, 3)"
    }
   ]
  },
  {
   "title": "Energy Harvested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "targets": [
    {
     "target": "aliasByNode(screeps.privateserver.energyHarvested, 3)"
    },
    {
     "target": "alias(movingAverage(screeps.privateserver.energyHarvested, '1d'), 'avg energyHarvested')"
    }
   ]
  },
  {
   "title": "Credit Production & Consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.privateserver.creditProduction"
    },
    {
     "target": "screeps.privateserver.creditConsumption"
    }
   ]
  },
  {
   "title": "Creeps Per Commune",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.privateserver.creepsPerRoom"
    },
    {
     "target": "movingAverage(screeps.privateserver.creepsPerRoom, '1d')"
    }
   ]
  },
  {
   "title": "Energy Spent on Creeps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.privateserver.energySpentOnCreeps"
    },
    {
     "target": "movingAverage(screeps.privateserver.energySpentOnCreeps, '1d')"
    }
   ]
  },
  {
   "title": "Credits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "aliasByNode(screeps.privateserver.credits, 3)"
    }
   ]
  },
  {
   "title": "Energy Spent On Construction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.privateserver.energySpentOnConstruction"
    },
    {
     "target": "movingAverage(screeps.privateserver.energySpentOnConstruction, '1d')"
    }
   ]
  },
  {
   "title": "Energy Spent on Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.privateserver.energySpentOnPower"
    },
    {
     "target": "movingAverage(screeps.privateserver.energySpentOnPower, '1d')"
    }
   ]
  },
  {
   "title": "Total Creeps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "screeps.privateserver.creeps" },
    {
     "target": "movingAverage(screeps.privateserver.creeps, '1d')"
    }
   ]
  },
  {
   "title": "CPU Per Creep",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.privateserver.cpuPerCreep"
    },
    {
     "target": "movingAverage(screeps.privateserver.cpuPerCreep, '1d')"
    }
   ]
  },
  {
   "title": "Power Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.privateserver.powerProcessed"
    },
    {
     "target": "movingAverage(screeps.privateserver.powerProcessed, '1d')"
    }
   ]
  },
  {
   "title": "Control Points",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.privateserver.controlPoints"
    },
    {
     "target": "movingAverage(screeps.privateserver.controlPoints, '1d')"
    }
   ]
  },
  {
   "title": "Minerals Harvested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.privateserver.mineralsHarvested"
    },
    {
     "target": "movingAverage(screeps.privateserver.mineralsHarvested, '1d')"
    }
   ]
  },
  {
   "title": "Energy Spent on Barricades",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.privateserver.energySpentOnBarricades"
    },
    {
     "target": "movingAverage(screeps.privateserver.energySpentOnBarricades, '1d')"
    }
   ]
  },
  {
   "title": "Ops Generated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.privateserver.opsGenerated"
    },
    {
     "target": "movingAverage(screeps.privateserver.opsGenerated, '1d')"
    }
   ]
  },
  {
   "title": "Energy Spent on Repairs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "screeps.privateserver.energySpentOnRepairs"
    },
    {
     "target": "movingAverage(screeps.privateserver.energySpentOnRepairs, '1d')"
    }
   ]
  }
 ]
}