import { Antifa } from './roleManagers/antifa/antifa'
import { Builder } from './roleManagers/commune/builder'
import { ControllerUpgrader } from './roleManagers/commune/controllerUpgrader'
import { FastFiller } from './roleManagers/commune/fastFiller'
import { Hauler } from './roleManagers/commune/hauler'
import { HubHauler } from './roleManagers/commune/hubHaulerManager'
import { Maintainer } from './roleManagers/commune/maintainer'
import { MeleeDefender } from './roleManagers/commune/meleeDefender'
import { MineralHarvester } from './roleManagers/commune/mineralHarvester'
import { SourceHarvester } from './roleManagers/commune/sourceHarvester'
import { AllyVanguard } from './roleManagers/international/allyVanguard'
import { Claimer } from './roleManagers/international/claimer'
import { Scout } from './roleManagers/international/scout'
import { Vanguard } from './roleManagers/international/vanguard'
import { VanguardDefender } from './roleManagers/international/vanguardDefender'
import { RemoteCoreAttacker } from './roleManagers/remote/remoteCoreAttacker'
import { RemoteDefender } from './roleManagers/remote/remoteDefender'
import { RemoteDismantler } from './roleManagers/remote/remoteDismantler'
import { RemoteHarvester } from './roleManagers/remote/remoteSourceHarvester'
import { RemoteHauler } from './roleManagers/remote/remoteHauler'
import { RemoteReserver } from './roleManagers/remote/remoteReserver'
import { Operator } from './powerCreeps/operator'

export const powerCreepClasses: { [key in PowerClassConstant]: any } = {
    operator: Operator
}
