{
 "title": "ServerStats",
 "time": { "from": "2022-08-09T18:21:52.682Z", "to": "2022-08-09T20:17:17.930Z" },
 "templating": {
  "list": [
   { "name": "Users", "query": "serverStats.*" },
   { "name": "Rooms", "query": "serverStats.$Users.$RoomType.*" },
   { "name": "RoomType", "query": "owned,reserved" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Controller level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(serverStats.$Users.$RoomType.$Rooms.controller.*.level, 1, 3)"
    },
    {
     "target": "aliasByNode(changed(serverStats.$Users.$RoomType.$Rooms.controller.*.timestamp), 6)"
    }
   ]
  },
  {
   "title": "Controller percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(divideSeriesLists(serverStats.$Users.$RoomType.$Rooms.controller.*.progress, #B), 1, 3)",
     "targetFull": "aliasByNode(divideSeriesLists(serverStats.$Users.$RoomType.$Rooms.controller.*.progress, serverStats.$Users.$RoomType.$Rooms.controller.*.progressTotal), 1, 3)"
    },
    {
     "refCount": 1,
     "target": "aliasByNode(movingAverage(changed(serverStats.$Users.$RoomType.$Rooms.controller.*.timestamp), 5), 6)"
    }
   ]
  },
  {
   "title": "Total creeps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "groupByNodes(currentAbove(movingAverage(removeBelowValue(serverStats.$Users.overviewStats.$Rooms.creepCounts, 2), 5), 1), 'sum', 1, 4)"
    }
   ]
  },
  {
   "title": "Total structures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "groupByNodes(serverStats.$Users.overviewStats.$Rooms.structureCounts.*, 'sum', 1, 4)"
    }
   ]
  },
  {
   "title": "CS Total progress %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(divideSeriesLists(groupByNodes(serverStats.$Users.$RoomType.$Rooms.constructionSite.*.progress, 'sum', 1, 3), #B), 5), 0, 1)",
     "targetFull": "aliasByNode(movingAverage(divideSeriesLists(groupByNodes(serverStats.$Users.$RoomType.$Rooms.constructionSite.*.progress, 'sum', 1, 3), groupByNodes(serverStats.$Users.$RoomType.$Rooms.constructionSite.*.progressTotal, 'sum', 1, 3)), 5), 0, 1)"
    },
    {
     "refCount": 1,
     "target": "aliasByNode(changed(serverStats.$Users.$RoomType.$Rooms.constructionSite.*.timestamp), 6)"
    }
   ]
  },
  {
   "title": "Energy in Spawn & Extensions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "target": "groupByNodes(movingAverage(serverStats.$Users.$RoomType.$Rooms.{spawn,extension}.*.store.energy, 5), 'sum', 1, 3)"
    },
    {
     "target": "groupByNodes(serverStats.$Users.$RoomType.$Rooms.{spawn,extension}.*.storeCapacityResource.energy, 'sum', 1, 3, 6)"
    },
    {
     "target": "aliasByMetric(changed(serverStats.$Users.$RoomType.$Rooms.{spawn,extension}.*.timestamp))"
    }
   ]
  },
  {
   "title": "User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(serverStats.$Users.user.lastUsedCpu, 5), 1)"
      }
     ]
    },
    {
     "title": "GCL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "target": "aliasByNode(serverStats.$Users.user.gcl, 1)"
      }
     ]
    },
    {
     "title": "CPU bucket",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "target": "aliasByNode(serverStats.$Users.user.cpuAvailable, 1)"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Controller level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "target": "aliasByNode(serverStats.$Users.$RoomType.$Rooms.controller.*.level, 1, 3)"
      },
      {
       "target": "aliasByNode(changed(serverStats.$Users.$RoomType.$Rooms.controller.*.timestamp), 6)"
      }
     ]
    },
    {
     "title": "Controller percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "target": "aliasByNode(divideSeriesLists(serverStats.$Users.$RoomType.$Rooms.controller.*.progress, #B), 1, 3)",
       "targetFull": "aliasByNode(divideSeriesLists(serverStats.$Users.$RoomType.$Rooms.controller.*.progress, serverStats.$Users.$RoomType.$Rooms.controller.*.progressTotal), 1, 3)"
      },
      {
       "refCount": 1,
       "target": "aliasByMetric(movingAverage(changed(serverStats.$Users.$RoomType.$Rooms.controller.*.timestamp), 5))"
      }
     ]
    }
   ]
  },
  {
   "title": "Creeps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Energy in creeps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(groupByNodes(serverStats.$Users.$RoomType.$Rooms.creep.*.store.energy, 'sum', 1, 3), 5), 0, 1)"
      },
      {
       "target": "aliasByMetric(changed(serverStats.$Users.$RoomType.$Rooms.creep.*.timestamp))"
      }
     ]
    },
    {
     "title": "Total creeps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "target": "groupByNodes(currentAbove(movingAverage(removeBelowValue(serverStats.$Users.overviewStats.$Rooms.creepCounts, 2), 5), 1), 'sum', 1, 4)"
      }
     ]
    },
    {
     "title": "Total parts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(groupByNodes(serverStats.$Users.$RoomType.$Rooms.creep.*.body.*, 'sum', 1, 3), 5), 0, 1)"
      },
      {
       "target": "aliasByMetric(changed(serverStats.$Users.$RoomType.$Rooms.creep.*.timestamp))"
      }
     ]
    },
    {
     "title": "Total parts per type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(groupByNodes(serverStats.$Users.$RoomType.$Rooms.creep.*.body.*, 'sum', 7), 5), 0)"
      },
      {
       "target": "aliasByMetric(changed(serverStats.$Users.$RoomType.$Rooms.creep.*.timestamp))"
      }
     ]
    }
   ]
  },
  {
   "title": "Structures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Energy in Spawn & Extensions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "target": "groupByNodes(movingAverage(serverStats.$Users.$RoomType.$Rooms.{extension,spawm}.*.store.energy, 5), 'sum', 1, 3)"
      },
      {
       "target": "groupByNodes(serverStats.$Users.$RoomType.$Rooms.{spawn,extension}, 'sum', 1, 3, 6)"
      }
     ]
    },
    {
     "title": "Total structures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "target": "groupByNodes(serverStats.$Users.overviewStats.$Rooms.structureCounts.*, 'sum', 1, 3)"
      }
     ]
    },
    {
     "title": "Energy in container",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "target": "groupByNodes(movingAverage(serverStats.$Users.$RoomType.$Rooms.container.*.store.energy, 5), 'sum', 1)"
      },
      {
       "target": "aliasByMetric(changed(serverStats.$Users.$RoomType.$Rooms.container.*.timestamp))"
      }
     ]
    },
    {
     "title": "Total structures per type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "groupByNodes(serverStats.$Users.overviewStats.$Rooms.structureCounts.*, 'sum', 5)"
      }
     ]
    }
   ]
  },
  {
   "title": "Construction sites",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total progress %",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(divideSeriesLists(groupByNodes(serverStats.$Users.$RoomType.$Rooms.constructionSite.*.progress, 'sum', 1, 3), #B), 5), 0, 1)",
       "targetFull": "aliasByNode(movingAverage(divideSeriesLists(groupByNodes(serverStats.$Users.$RoomType.$Rooms.constructionSite.*.progress, 'sum', 1, 3), groupByNodes(serverStats.$Users.$RoomType.$Rooms.constructionSite.*.progressTotal, 'sum', 1, 3)), 5), 0, 1)"
      },
      {
       "refCount": 1,
       "target": "aliasByMetric(changed(serverStats.$Users.$RoomType.$Rooms.constructionSite.*.timestamp))"
      }
     ]
    }
   ]
  },
  {
   "title": "Source",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Source energy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "target": "aliasByNode(movingAverage(serverStats.$Rooms.*.$Rooms.source.*.energy, 5), 1, 3, 5)"
      },
      {
       "target": "aliasByMetric(changed(serverStats.$Rooms.*.$Rooms.source.*.timestamp))"
      }
     ]
    }
   ]
  },
  {
   "title": "Dropped energy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Energy on ground",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "target": "groupByNodes(movingAverage(serverStats.$Rooms.overviewStats.$Rooms.droppedEnergy, 5), 'sum', 1, 3)"
      }
     ]
    }
   ]
  },
  {
   "title": "Mineral",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mineral amount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "target": "groupByNodes(serverStats.$Rooms.*.$Rooms.mineral.*.mineralAmount, 'sum', 1, 3)"
      },
      {
       "target": "aliasByMetric(changed(serverStats.$Rooms.*.$Rooms.mineral.*.timestamp))"
      }
     ]
    }
   ]
  },
  {
   "title": "Tombstone",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resources in tombstones",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "target": "groupByNodes(movingAverage(serverStats.$Rooms.*.$Rooms.tombstone.*.store.*, 5), 'sum', 1, 3, 7)"
      },
      {
       "target": "aliasByMetric(changed(serverStats.$Rooms.*.$Rooms.tombstone.*.timestamp))"
      }
     ]
    }
   ]
  }
 ]
}