{
 "title": "Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Users", "query": "stats.*" },
   { "name": "Shards", "query": "stats.$Users.*" },
   { "name": "RoomType", "query": "stats.$Users.$Shards.rooms.*" },
   {
    "name": "Rooms",
    "query": "stats.$Users.$Shards.rooms.$RoomType.*"
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cpu percentage used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(divideSeriesLists(stats.$Users.$Shards.cpu.usage, #B), 1)",
     "targetFull": "aliasByNode(divideSeriesLists(stats.$Users.$Shards.cpu.usage, stats.$Users.$Shards.cpu.limit), 1)"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "refCount": -1,
     "target": "aliasByNode(stats.$Users.$Shards.cpu.usage, 1)"
    }
   ]
  },
  {
   "title": "Memory percentage used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(divideSeriesLists(stats.$Users.$Shards.memory.usage, #B), 1)",
     "targetFull": "aliasByNode(divideSeriesLists(stats.$Users.$Shards.memory.usage, stats.$Users.$Shards.memory.limit), 1)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "refCount": -1,
     "target": "aliasByNode(stats.$Users.$Shards.memory.usage, 1)"
    }
   ]
  },
  {
   "title": "Global Control Level",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(stats.$Users.$Shards.gcl.level, 1)"
    }
   ]
  },
  {
   "title": "Global Power Level",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "aliasByNode(stats.$Users.$Shards.gpl.level, 1)"
    }
   ]
  },
  {
   "title": "CPU bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "target": "aliasByNode(stats.$Users.$Shards.cpu.bucket, 1)"
    }
   ]
  },
  {
   "title": "GCL Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(divideSeriesLists(stats.$Users.$Shards.gcl.progress, #B), 1)",
     "targetFull": "aliasByNode(divideSeriesLists(stats.$Users.$Shards.gcl.progress, stats.$Users.$Shards.gcl.progressTotal), 1)"
    }
   ]
  },
  {
   "title": "GPL Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(divideSeriesLists(stats.$Users.$Shards.gpl.progress, #B), 1)",
     "targetFull": "aliasByNode(divideSeriesLists(stats.$Users.$Shards.gpl.progress, stats.$Users.$Shards.gpl.progressTotal), 1)"
    }
   ]
  },
  {
   "title": "Leaderboard Rank",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(stats.$Users.$Shards.leaderboard.rank, 1)"
    }
   ]
  },
  {
   "title": "Credits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(stats.$Users.$Shards.resources.credits, 1)"
    }
   ]
  },
  {
   "title": "Pixels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(stats.$Users.$Shards.resources.pixels, 1)"
    }
   ]
  },
  {
   "title": "Construction site count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(stats.$Users.$Shards.constructionSiteCount, 1)"
    }
   ]
  },
  {
   "title": "Tick duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(averageSeries(removeAboveValue(stats.$Users.$Shards.tickLength, 100000)), 'Tick duration')"
    }
   ]
  },
  {
   "title": "Last Global reset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "target": "aliasByNode(stats.$Users.$Shards.lastReset, 1)"
    }
   ]
  },
  { "title": "Rooms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Cpu used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$RoomType.$Rooms.cu, 5)), 1, 4, 5)"
    }
   ]
  },
  {
   "title": "Controller level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(removeBelowValue(stats.$Users.$Shards.rooms.$RoomType.$Rooms.cl, 1)), 1, 5)"
    }
   ]
  },
  {
   "title": "Creep count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$RoomType.$Rooms.cc, 5)), 1, 4, 5)"
    }
   ]
  },
  {
   "title": "Spawn Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "aliasByNode(movingAverage(stats.$Users.$Shards.rooms.$RoomType.$Rooms.su, 5), 1, 5)"
    }
   ]
  },
  {
   "title": "Energy stored",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "target": "removeZeroSeries(aliasByNode(averageAbove(stats.$Users.$Shards.rooms.commune.$Rooms.es, 0), 1, 4, 5))"
    }
   ]
  },
  {
   "title": "Minerals harvested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "target": "removeZeroSeries(aliasByNode(stats.$Users.$Shards.rooms.$RoomType.$Rooms.mh, 1, 5))"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Energy output - Build",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$RoomType.$Rooms.eob, 5)), 1, 4, 5)"
    }
   ]
  },
  {
   "title": "Energy output - Spawn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$RoomType.$Rooms.eosp, 5)), 1, 4, 5)"
    }
   ]
  },
  {
   "title": "Energy output - Upgrade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$RoomType.$Rooms.eou, 5)), 1, 4)"
    }
   ]
  },
  {
   "title": "Energy output - Repair Other",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$RoomType.$Rooms.eoro, 5)), 1, 4)"
    }
   ]
  },
  {
   "title": "Energy output - Repair Wall/Rampart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$RoomType.$Rooms.eorwr, 5)), 1, 4)"
    }
   ]
  },
  {
   "title": "Energy output - TOTAL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "targets": [
    {
     "target": "groupByNodes(removeZeroSeries(movingAverage(group(#A, #B, #C, #D, #E), 5)), 'sum', 0, 1)",
     "targetFull": "groupByNodes(removeZeroSeries(movingAverage(group(aliasByNode(stats.$Users.$Shards.rooms.$RoomType.$Rooms.eob, 1, 4), aliasByNode(stats.$Users.$Shards.rooms.$RoomType.$Rooms.eoro, 1, 4), aliasByNode(stats.$Users.$Shards.rooms.$RoomType.$Rooms.eorwr, 1, 4), aliasByNode(stats.$Users.$Shards.rooms.$RoomType.$Rooms.eoso, 1, 4), aliasByNode(stats.$Users.$Shards.rooms.$RoomType.$Rooms.eosp, 1, 4)), 5)), 'sum', 0, 1)"
    }
   ]
  },
  {
   "title": "Energy input - Harvest",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
   "targets": [
    {
     "target": "aliasByNode(removeZeroSeries(movingAverage(stats.$Users.$Shards.rooms.$RoomType.$Rooms.eih, 5)), 1, 4, 5)"
    }
   ]
  }
 ]
}